name: ProjectEGM722v2
author: Kiri Braisher
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas=2.2.2
  - geopandas=0.14.2
  - numpy=1.26.4
  - matplotlib=3.8.4
  - shapely=2.0.4
  - pathlib=1.0.1
  - rasterio=1.3.9
  - earthaccess=0.9.0
  - colorama=0.4.6
  - scipy=1.13.0
