name: ProjectEGM722v2
author: Kiri Braisher
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - geopandas
  - numpy
  - matplotlib
  - shapely
  - pathlib
  - rasterio
  - osgeo
  - earthaccess
  - colorama
  - scipy
