name: ProjectEGM722v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - geopandas
  - numpy
  - matplotlib
  - shapely
  - pathlib
  - rasterio
  - earthaccess
  - osgeo
  - os
  - math
  
  